name: Build

on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup LXD
        uses: whywaita/setup-lxd@v1
        with:
          lxd_version: latest/stable

      - name: Install rockcraft
        run: |
          sudo snap install --classic --channel edge rockcraft
      - name: Build ROCK
        run: rockcraft pack --verbose

      - name: Upload locally built ROCK artifact
        uses: actions/upload-artifact@v3
        with:
          name: magma-orc8r-controller-rock
          path: "magma-orc8r-controller_*.rock"
