name: Push (any)

on:
  push:
    branches-ignore:
      - "main"

jobs:

  lint-report:
    uses: ./.github/workflows/lint-report.yaml

  static-analysis:
    uses: ./.github/workflows/static-analysis.yaml

  build:
    uses: ./.github/workflows/build.yaml

  test:
    needs: build
    uses: ./.github/workflows/test.yaml
