name: Push (main)

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  test:
    needs: build
    uses: ./.github/workflows/test.yaml

  publish:
    needs: test
    uses: ./.github/workflows/publish.yaml
